# Generated by Django 5.0 on 2023-12-12 13:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='uploads/video_files', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])])),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('dictionary_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Videos.dictionary')),
            ],
        ),
    ]
