# Generated by Django 5.0 on 2023-12-12 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Videos', '0002_signvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='best_video',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Videos.signvideo'),
        ),
        migrations.AddField(
            model_name='dictionary',
            name='num_videos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='signvideo',
            name='converted_numpy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='signvideo',
            name='is_best',
            field=models.BooleanField(default=False),
        ),
    ]
